version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5544:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # чтобы данные сохранялись

volumes:
  pgdata:
